   name: Team Approval Check

   on:
     pull_request_review:
       types: [submitted]
       
   permissions:
     contents: read
     pull-requests: read
     issues: read
  
   jobs:
     approval-check:
       runs-on: ubuntu-latest
       steps:
         - name: Check Team Approvals
           uses: jefeish/github-action-team-approval@main
           with:
             team_name: a-team
             required_approvals: 1
             token: ${{ secrets.GH_ADMIN_SECRET }}
